### ISSUE TITLE
What is the origin of the 0.3% THC distinction?

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#10]

**Comment by wdlngtn** [comment]
This cut off has NOTHING to do with drug use or potential for addiction. It comes from Small's research and then publicized in a taxonomy paper.
https://www.jstor.org/stable/pdf/4253607.pdf?refreqid=excelsior%3A82c35d3280bdf55d40906ac9d47859a5
The .3% number generated to explain the THC/CBD content of a bunch of cannabis varieties in a graph (Figure 8). The research examined a collection of "350 different viable seed stocks from about 50 countries" grown in Ottawa Canada one summer - which happened to be a drought year. They found that most varieties with high CBD had THC lower than .3%; likewise, most drug varieties have CBD below .5%. They also only had 3 of the 350 test over 2% THC, and it looks like at least half of the non-drug plants would have gone over .3%. The highest mean for any population is 1.5% THC. There is no world this study can reflect the plants we have today. I will say that there are a lot of 0% THC plants, and that's interesting.
In the discussion they mention their plants had less resin (cannabinoid oil) than plants would if grown in their home range. They also mentioned the marijuana they got from Mississippi has twice the THC content their (3%) than in Ottawa (1.5%)
He mentions the .3% cutoff again in a widely cited review paper in 1976 where he is arguing hemp and marijuana are different subspecies of C sativa. That's where Canadian policy makers got .3% from, and the rest is history. That paper says
"
It will be noted that we arbitrarily adopt a concentration of 0.3% 9-THC
(dry weight basis) in young, vigorous leaves of relatively mature plants as a
guide to discriminating two classes of plants.

**Comment by wdlngtn** [comment]
Excellent link for this answer.

https://www.hemp.com/2018/09/where-did-0-3-thc-so-called-hemp-definition-come-from-canada/
