### ISSUE TITLE
What is the current status of somatic and embryotic tissue culture?

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#13]

**Comment by wdlngtn** [comment]
Currently, it's not feasible plant regenerate hemp genotypes from anything but seed or cuttings of green tissue. 

Although hemp and marijuana are easily propagated through shoot cuttings (oft called tissue culture in internet searches), hemp has never been regenerated from a callus (despite decades of intense research). At the recent conference I attended, we learned some companies and forerunner labs have made small steps toward true tissue culture, but none have succeeded or expect to succeed anytime soon at regeneration from a callus.
