### ISSUE TITLE
Upload Season 1 Data

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#19]
- [x] Variety by planting location table
- [x] Complete planting date table

Add to list as per #16. Comment here as an update on progress.

**Comment by wdlngtn** [comment]
[PlotVarietyFile.xlsx](https://github.com/TREC-Agroecology/hemp/files/3799147/PlotVarietyFile.xlsx)

tab one is the plot location by variety info. tab 2 is a collection of the planting guides for a map.

**Comment by brymz** [comment]
Two `.csv`s uploaded to the `data/` file of the repo, please.
