### ISSUE TITLE
Coordinates of 2019 plantings

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#25]
- PP1 and Variety trial
NE corner: 25.5106648, -80.5035612
NW corner: 25.5106533, -80.5037365
SE corner: 25.5100130, -80.5035226
SW corner: 25.5100191, -80.5037158 

- 3rd planting
NE corner: 25.5109193, -80.5035418
NW corner: 25. 5108739, -80.5037446
SE conrner: 25.5108019, -80.5035491
SW corner: 25.518270,-80.5307704

- 4th planting
NE corner: 25.5103072, -80.5037050
NW corner: 25.5102963, -80.5038868 
SE corner: 25.5100191, -80.5037158
SW corner: 25.5099958, -80.5039116

**Comment by brymz** [comment]
Thanks, Daniel.
Can we put this in the wiki or as a data table?
