### ISSUE TITLE
Clean messy data

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#32]
- `Month` to integer
- `Block` as 1:21
- `VarietyTrial1_summer_2019_Emergence.csv`
   - `Column` mispelled
   - 2 entries for `Day`
- `Flowering` extra column, `PilotPlot2$Block`

**Comment by lmonserrate** [comment]
I have made the changes you requested for the hemp data plus some I have found. I just have questions about the following changes:

•	`Block` as 1:21
•	`Flowering` extra column, `PilotPlot2$Block`

What did you mean exactly by `Block` as 1:21?

I was not able to find an extra column in any of our flowering data sheet. Could you indicate which file you meant? And also what does `PilotPlot2$Block` mean? 

Thanks

**Comment by brymz** [comment]
> What did you mean exactly by Block as 1:21?

`PlotVarietyList.csv` has values of `Block` from `1` to `21`. This is not consistence with several of the other data files (e.g., `PilotPlot2$Block`).

> I was not able to find an extra column in any of our flowering data sheet.

Ok. I'll not it more specifically next time I work with the data. The extra column appears when you import the data to R.
