### ISSUE TITLE
Clean up flowering time data

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#36]
![flower_variety](https://user-images.githubusercontent.com/1743560/75262067-f89fa600-57b9-11ea-83f8-2884e9fa6353.png)
![flower_pilot](https://user-images.githubusercontent.com/1743560/75262075-fb020000-57b9-11ea-8fb6-98db4e9a20a4.png)

**Comment by wdlngtn** [comment]
I think the pilot 1 should be good.  I will proceed with the rest. I'm seeing plenty of entry errors, but only entry errors. No underlying issue other than the person writing notes or typing made a mistake.

**Comment by wdlngtn** [comment]
I cleaned up flowering data for each of the 4 experiments.

**Comment by brymz** [comment]
Super!

**Comment by brymz** [comment]
Something happened with the PilotPlot2 data.

![flower_variety](https://user-images.githubusercontent.com/1743560/75926799-28455280-5e39-11ea-9eaa-aa5df63b11aa.png)
![flower_pilot](https://user-images.githubusercontent.com/1743560/75926813-2ed3ca00-5e39-11ea-9fe1-e72580baa4e5.png)

**Comment by wdlngtn** [comment]
I think it's an issue with the blocks. they are repeated in the document. I can fix now.

**Comment by brymz** [comment]
Looks good!
![flower_pilot](https://user-images.githubusercontent.com/1743560/75989266-f7a8fb80-5ec0-11ea-8e5c-6795b821ca6b.png)
