### ISSUE TITLE
Set up communication plan and decision tree for email/call-in filters

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#5]
- Emails should go to `hemp@ifas.ufl.edu`
- Graduate student / Extension agent team have first filter
   - Zack - high-profile and/or direct relevance to research plan
   - UFF - general relevance with clear intent for resource and/or funding support
   - Site leader - farmer with enthusiasm | interest to volunteer | proximity to research location
   - Roger - propagation | indoor production
   - ??? - plant extracts | quality testing
   - Direct to website - general request for information

**Comment by brymz** [comment]
Media to Ruth:

"Thanks for your interest in the UF/IFAS Industrial Hemp Pilot Project. Dr. Ruth Borger,  Asst. Vice President for UF/IFAS Communications (rborger@ufl.edu) is handling our media inquiries. She is cc’d on this email, but you may want to reach out to her again next week as she is currently out of the country."

**Comment by wdlngtn** [comment]
Should plant extra Questions go to Bonnie still ? @brymz

**Comment by brymz** [comment]
Moved to wiki: https://github.com/TREC-Agroecology/hemp/wiki/Communication-Plan
