### ISSUE TITLE
Day Length Figure

### ISSUE THREAD

**Issue by wdlngtn** [TREC-Agroecology/hemp#7]
We should make a figure to represent day length differences by latitude.

I am attaching a csv with the number of 13.5 and 14.5 hour days per latitude.  Also, is the excel sheet I used to calculate for each latitude.

How can we best process this data into a final figure?

Will

**Comment by wdlngtn** [comment]
[DaylengthData.xlsx](https://github.com/TREC-Agroecology/hemp/files/2916193/DaylengthData.xlsx)

**Comment by wdlngtn** [comment]
[DaylengthData.xlsx](https://github.com/TREC-Agroecology/hemp/files/2958629/DaylengthData.xlsx)

I added days with 14 hours because more lit refers to 14 hour days.  I think using all three will be dramatic though.  Check out Florida's issue on the 14 hour day data set.  We got screwed!

**Comment by wdlngtn** [comment]
| DwL>13.5 | DWL>14 | DWL>14.1 | DWL>14.5
-- | -- | -- | -- | --
Quincy (31.8 N) | 97 | 51 | 38 | 0
Gainesville (29.6 N) | 87 | 24 | 0 | 0
Apopka (28.7 N) | 82 | 0 | 0 | 0
Homestead (25.5 N) | 60 | 0 | 0 | 0

**Comment by brymz** [comment]
I think we've identified the winning composition of the figure. Do you still need help putting the publication version together?

**Comment by brymz** [comment]
I think you made good progress on this for the review paper. Are you still looking for something different? If not, you can close the issue.

**Comment by wdlngtn** [comment]
I will close for the review, Possibly I will make another one for FLorida for the research paper - that will be a single effort and not an issue.

WE DID IT!
Close
