### ISSUE TITLE
2021 Hemp plantings - quick overview

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#73]
All experiments will have 30-40' buffers plus 12' sorghum screenings on all sides.
_
Block 1
_
NW corner.
Nitrogen Trial - Grain and Fiber. – 5/6 or 5/11.
3 varieties x 6 rates x 4 reps. (18 trt).
Field size: L 242' x W 160’. (0.89 ac). 
Plot size: L 25' x W 12'.  (300 sqft).

NE corner. Below/ adjacent agroecosystems plot. 
Herbicide Trial. – 5/25.
1 variety x 2 reps. 50' buffer between.
Field size: L 25' x W 100'. (0.06 ac). 
Plot size: L 22.5' x W 22.5'. (500 sqft).  

Middle.
Phosphorous Trial - Grain and Fiber. – 5/13-14.
1 variety x 5 rates x 4 reps. (20 trt). 
Field size: L 118' x W 84'. (0.23 ac).
Plot size: L 25' x W 12'.  (300 sqft).

SE Corner. 
Planting Date - Early. – 4/27, and 5/18.
6 varieties x 4 reps x 2 dates. (20 trt). 
Field size: L 75' x W 42'. 
Plot size: L 10' x W 6'. (60 sqft).
*Total area: L 75' x W 84'. (0.14 ac).

SW Corner. 
Planting Date - Late. – 7/..,8/..
6 varieties x 4 reps x 2 dates. (24 trt). 
Field size: L 75' x W 42'. 
Plot size: L 10' x W 6'. (60 sqft).
*Total area: L 75' x W 84'. (0.14 ac).

**Total area for both Planting Dates: L 70' x W 168'. (0.28 ac). 

_
Block 10
_
Eastside. 
Nitrogen Trial - EO. – 5/6 or 5/11.
3 varieties x 6 rates x 4 reps. (18 trt).
Field size: L 242' x W 160’. (0.89 ac). 
Plot size: L 25' x W 12'.  (300 sqft).

**Comment by Danielcalza** [comment]
Please review - I actually think the planting date studies can fit in the lower south end of block 1 but will confirm today with more field measurements.  @brymz @AjitWX

**Comment by brymz** [comment]
> I actually think the planting date studies can fit in the lower south end of block 1

I would prefer that.

**Comment by Danielcalza** [comment]
> I would prefer that.

Great news. They can all fit perfectly and with the optimal 40' buffers plus 12' sorghum screening (2 - 6' strips, staggered plantings).
