### ISSUE TITLE
Add Important Project Documents to Dropbox Folder

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/hemp#8]
- [x] Research plan
- [x] Add-on plan
- [x] MREC plan
- [x] GCREC plan
- [x] Transport Policy (Citra and MREC versions)
- [x] DEA permit
- [x] FDACS permit * 11
- [x] Varieties list/log
- [x] Field planting plan/protocol

**Comment by wdlngtn** [comment]
Current field plans are added.  Field protocols will be added/evolved over the next month.
