### ISSUE TITLE
Grain & Fiber N Study 2022 SOP

### ISSUE THREAD

**Issue by AjitWX** [TREC-Agroecology/hemp#81]
### Project Overview

To Do: Review [check list](https://github.com/TREC-Agroecology/hemp/issues/84)

Project Objectives - To determine EO hemp (Cannabis sativa) response to applied nitrogen.
    Project Description - Grain & Fiber N Study
    Project Protocol - 3 varieties x 6 rates x 4 reps. (18 trt). (72 plots.)
Field size: L 242' x W 160’. (0.89 ac).
Plot size: L 25' x W 12'. (300 sqft).
    Field Design - RCB with 4 reps. Blocked by replication.
    Field Diagrams - Maps can be found on TEAMS.
    Projected Start Date- Early May.
    Projected End Date- September/October.
    Project Manager(s)- Ajit, Tamara, Daniel.
    Projected Planting Date- 5/18-19. 
    Crop(s)- Hemp: Essential oil - cv. Abound, SS-Beta, Yuma
    Irrigation - Solid set: over-head sprinklers.
    Applications - Six (6) Nitrogen treatments, split between **four (4) applications.
    Planting methods - Center of mounds. Earthway manual mechanical seeder.
    Data Collection & Sampling -
    Project Maintenance - Weeding as needed. 
    Equipment needed - Moldboard plow, Harrow disk, raised bed shaper, roto-tiller, herbicide wagon, others - TBD.
    Field crew assistance - Yes. For irrigation and land preparation.
_
### Land Request

    Preferred block- Block 1.
    Section- South.
    Area/Acres requested-L 242' x W 160’. (0.89 ac).
    Greenhouse - No. 
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Complete TREC Land Request
-[] Complete TREC Greenhouse Request
-[] Request faculty sponsor to complete UFarm request.
_
### Land Preparation

 Cultivation (mowing, moldboard plow, disc and level the field, form raised beds, drilling holes, etc.) - Standard 
 cultivation.
 Row Length - L 25' x W 12'. (300 sqft).
 In-Row Spacing - ?
 Between-Row Spacing - 1.5' 
 Field Buffers - 30-40'. 
 Seeding? (Direct, Broadcast, Incorporated, Drill, Earthway, etc.) - Yes. Earthways.
 Transplants? - No. 
 Support Structure (Rebar, String, etc.) - No.
 Plastic Mulch? - No. 
 Full image of field layout, design, and plot arrangement - Maps and layouts can be found on TEAMS.
 Date to complete land preparation - 5/17-18. 
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Complete TREC field preparation request
-[] Row Crop
-[] Plastic Culture
_
### Irrigation

    Drip Tape? (drip placement, emitter spacing, flow-rate GPM/100 ft., etc.) - Drip tape. Two lines per bed. 
    Solid set? (overhead irrigation, micro-sprinkler) - Solid set - overhead.
    Irrigation Timing (frequency and trigger) - As needed*
       *[Once per week for the first 2-3 weeks to germinate and establish**].
    Irrigation Amount (per application) - 1 inch.
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Complete TREC fieldwork request for irrigation.
_
### Fertilizer Application

    Label Name - Urea (N), Triple Super Phosphate (P), Sulfate of Potash (K)
    Analysis rates (NPK, etc.) - 46-0-0 (N), 0-46-0 (P), 0-0-50 (K)
    Application rate per acre:
- Urea (N)
     0 lbs N/ac 
    50 lbs N/ac
    100 lbs N/ac
    150 lbs N/ac
    200 lbs N/ac
    250 lbs N/ac. TSP
- Triple Super Phosphate (P)
    60 lbs P2O5/ac
- Sulfate of Potash (K)
    300 lbs K2O/ac

    Application method (banded on top of the bed, soil incorporation, etc.) - Pre-plant incorporated - except nitrogen.
    Application timing and frequency - TBD.
    Lab or field personnel - Ajit, Tamara, Daniel.
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Fertilizer request form
_
### Herbicide Application

    Label Name - Dual Magnum.
    Active ingredient(s) and concentration - S-metolachlor, benoxacor.
    Resistance Management: Group 15 Herbicide.
    Restricted Entry Interval (REI): 24 hours.
    Application rate per acre - 1 pint.
    Application method (pre-plant broadcast incorporated, shank or drip applied, etc.) - pre-planting, sprayer.
    Application timing and frequency - Once at pre-planting.
    Lab or field personnel - Daniel, Ajit, Jacob.
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Worker Protection Standard Training
-[] Review "Training Workers and Handlers under the 2016 Revision Requirements" by Frederick M. Fishel.
-[] Found in the TREC network Unit drive > TREC Pesticide Use information > WPS information
-[] Pesticide/Herbicide request form
_
### Project Maintenance Events

    Research treatment application - Six (6) Nitrogen treatments, split between **four (4) applications. - TBD.
    Weeding - PRE: Dual Magnum.** POST: cultivation or hooded applications.
    Scouting - Weekly.
    Sampling -
    Harvesting and Sampling -
    Project removal - September/ October. 
_
To Do: Update [check list](https://github.com/TREC-Agroecology/hemp/issues/84)
-[] Equipment Request
-[] Complete TREC fieldwork request well ahead of maintenance events.
_
### Data Collection & Sampling

    Database - TEAMS, GitHub.
    Data type:
    Rainfall, irrigation, temperature
    Soil moisture
    Mehlich 3 P, pre-plant, 0-6”, block-level
    Total N (dry combustion), pre-plant, 0-6”, block-level
    NO3- & NH4+, pre-plant, 0-6”, block-level
    SOM, pre-plant, 0-6”, block-level
    Soil water holding capacity
    Plants/m2 after emergence
    Leaf tissue nutrient concentrations (N & P) i. Stage 1 ii. Stage 2 iii. Stage 3 iv. Stage 4 v. Stage 5
    Biomass at harvest 
    Yield, moisture, test weight 
    Mehlich 3 P, post-harvest, 0-6”, plot-level 
    Total N (dry combustion), post-harvest, 0-6”, plot-level 
    NO3- & NH4+, post-harvest, 0-6”, plot-level 
    SOM, post-harvest, 0-6”, plot-level.
    Data storage -
    Metadata -
    Data collection -
    Protocols -
    Timing -
    Logistics -
    Sample processing and analysis -
_
### Contingencies

  What important decisions are next to be made or remain a challenge?
- Predicting weather patterns. 
- Making progress despite weather delays/ shifting efforts. 

What could possibly go wrong?
- Weather delays.
- Changes to experiment, field design/ layout. 
- Equipment issues/ calibration delays.

**Comment by Danielcalza** [comment]
@Tamara729
