### ISSUE TITLE
Weather station soil probes - placement and timing 

### ISSUE THREAD

**Issue by Danielcalza** [TREC-Agroecology/hemp#88]
Block 1
- GF-N
- Three stations: Random thought out the field. 
- Placement:  Within mounds, on E/W buffers.  
- Timing:  ASAP after planting.

Block 10
- Flower-N
- Three stations: Random thought out the field. 
- Placement: Two within mounds, on E/W buffers, breaking through the plastic mulch, and two on the open buffers.
- Timing: ASAP after planting.

**Comment by Danielcalza** [comment]
@tamara729

**Comment by brymz** [comment]
Let's make placement so we can track irrigation AND precipitation. So three to BK 1 and four to BK 10. In BK 10, two should go on the mounds and two on the open buffers. ASAP after planting is a good goal.
